install.packages("readxl")
library(readxl)
data <- read.csv(file.choose())
head(data)
names(data)
cor(data$sleep_hours,data$stress_level)
install.packages("ggplot2")
library(ggplot2)
ggplot(data,aes(x=sleep_hours,y=stress_level))+geom_point()+geom_smooth(method="lm")+ggtitle("Sleep vs Stress Level")
table(data$mental_state)
ggplot(data,aes(x=mental_state))+geom_bar()+ggtitle("Distribution of Mental State")
aggregate(stress_level~mental_state, data=data,mean)
aggregate(anxiety_level~mental_state,data=data,mean)
aggregate(sleep_hours~mental_state, data=data,mean)
ggplot(data, aes(x = mental_state, y = sleep_hours)) +
  geom_boxplot() +
  ggtitle("Sleep Hours across Mental States")
anova_model <- aov(stress_level ~ mental_state, data = data)
summary(anova_model)
model <- lm(stress_level ~ sleep_hours + anxiety_level, data = data)
summary(model)
aggregate(stress_level ~ mental_state, data = data, sd)
